# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('bio', models.CharField(max_length=255)),
                ('especiality', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, upload_to=b'')),
                ('email', models.EmailField(max_length=254)),
                ('curriculum', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, upload_to=b'')),
                ('dtex', models.CharField(max_length=255)),
                ('dimg', models.CharField(max_length=255)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webinfo.Developer')),
            ],
        ),
    ]
